INSERT INTO TiposProductos (nombre_tipo_producto, descripcion_tipo_producto, fechas_registro) VALUES 
('Electrónicos', 'Productos electrónicos como televisores, smartphones, etc.', GETDATE()),
('Ropa', 'Diferentes tipos de prendas de vestir.', GETDATE()),
('Alimentos', 'Productos alimenticios y bebidas.', GETDATE()),
('Muebles', 'Mesas, sillas y otros tipos de muebles.', GETDATE()),
('Libros', 'Libros de diferentes géneros y autores.', GETDATE());
